version: "3.9"

volumes:
  vol-emqx-data:
    name: foo-emqx-data
  vol-emqx-etc:
    name: foo-emqx-etc
  vol-emqx-log:
    name: foo-emqx-log

services:
  flask:
    container_name: flask
    build:
      context: .
    #restart: unless-stopped
    environment:
      APP_ENV: development # TODO later on we can create a .yml file specifically for production
      MONGODB_USERNAME: ${MONGODB_USERNAME:-user} # TODO currently the user is the root. Ideally we should have a separate user for the app
      MONGODB_PASSWORD: ${MONGODB_PASSWORD:-DEFAULT_PASSWORD_DO_NOT_USE}
      MONGODB_HOSTNAME: ${MONGODB_HOSTNAME:-mongodb}
      MONGODB_PORT: 27017
      MONGODB_DATABASE: ${MONGODB_DATABASE:-HoT}
      MQTT_BROKER: ${MQTT_BROKER:-broker.emqx.io}
      MQTT_PORT: ${MQTT_PORT:-1883}
      MQTT_USERNAME: ${MQTT_USERNAME:-emqx}
      MQTT_PASSWORD: ${MQTT_PASSWORD:-DEFAULT_PASSWORD_DO_NOT_USE}
    volumes:
      - .:/app/backend
    ports:
      - 5000:5000
    depends_on:
      - mongodb
      - emqx
    networks:
      - backend
  
  emqx:
      image: emqx:5.0.23
      environment:
        EMQX_NAME: ${MQTT_USERNAME:-emqx}
        EMQX_HOST: ${MQTT_BROKER:-broker.emqx.io}
      volumes:
        - vol-emqx-data:/opt/emqx/data
        - vol-emqx-etc:/opt/emqx/etc
        - vol-emqx-log:/opt/emqx/log
      ports: 
        - ${MQTT_PORT:-1883}:1883
        - 18083:18083
        - 8083:8083
        - 8084:8084
        - 8883:8883
      networks:
        emqx-bridge:
          aliases:
          - ${MQTT_BROKER:-broker.emqx.io}

  mongodb:
    image: mongo:6.0.4
    container_name: mongodb
    #restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME:-user}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD:-DEFAULT_PASSWORD_DO_NOT_USE}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE:-HoT}
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - backend

networks:
  backend:
    driver: bridge
  emqx-bridge:
    driver: bridge
